import logging
import re
import streamlit as st
from llm import ChatLLM, ChatMedLLM
from collections import defaultdict
from typing import Dict, List
from streamlit_feedback import streamlit_feedback
from google.cloud import bigquery as bq
from io import StringIO
from datetime import datetime
from config import CONFIG
import json
import logging
import uuid
import hashlib
import pwd
import os
import pandas as pd
import pprint
from streamlit_js_eval import streamlit_js_eval
from pypdf import PdfReader

st.set_page_config(layout="wide")


def encrypted_id() -> str:
    """
    Create an encrypted id for user
    """
    m = hashlib.md5()
    user_name = pwd.getpwuid(os.getuid())[0]
    m.update(user_name.encode('utf-8'))
    return (str(int(m.hexdigest(), 16))[0:12])


def refresh_page() -> None:
    streamlit_js_eval(js_expressions="parent.window.location.reload()")


def disable_inputs():
    st.session_state.disabled = True

def record_feedback_in_BQ(feedback) -> None:
    """
    Record the feedback
    :param records: dictionary with the feedback
    :param table_id: bigquery table id
    :return: None
    """
    client = bq.Client()
    errors = client.insert_rows_json(CONFIG.bq_feedback_table, [feedback])
    if errors == []:
        st.sidebar.success("Thanks for your feedback!")
    else:
        st.sidebar.error(("Encountered errors while inserting rows: {}".format(errors)))



st.markdown("<img src='https://bridgebio.com/wp-content/themes/bridgebio/assets/img/logo-alt.png' width='200' style='display: block; margin:0 auto;'>" , unsafe_allow_html=True)
st.markdown('<h3 style="text-align: center;">Your research assistant</h3>', unsafe_allow_html=True)
st.markdown('<div style="text-align: left;font-size: 20px;"><b>*Disclaimer</b>: This application is for internal testing only. Please, ignore any output generated by this application for answering real patient-related medical questions.</div>', unsafe_allow_html=True)
st.subheader(" ")



with st.sidebar:
    st.write(f"I am a research assistant.")
    "Powered by [Gemini](https://gemini.google.com/corp/app) and [MedLM](https://cloud.google.com/blog/topics/healthcare-life-sciences/introducing-medlm-for-the-healthcare-industry)"

def initialize_chat():
    if "messages" not in st.session_state:
        st.session_state.messages = []

initialize_chat()

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"], unsafe_allow_html=True)

agent = ChatLLM()
med_agent = ChatMedLLM()

uploaded_files = st.file_uploader(
    "Optional: Choose a pdf file", accept_multiple_files=True, type=('pdf')
)
pdf_data = {}
for uploaded_file in uploaded_files:
    print(uploaded_file)
    reader = PdfReader(uploaded_file)
    number_of_pages = len(reader.pages)
    pdf_data[uploaded_file.name] = reader.pages[0].extract_text()
    for n in range(1, number_of_pages):
        page = reader.pages[n]
        pdf_data[uploaded_file.name]+= page.extract_text()

if prompt := st.chat_input():

    # Display user message in chat message container
    with st.chat_message("user"):
        st.markdown(prompt)
    # Add user message to chat history
    st.session_state.messages.append({"role": "user", "content": prompt})

    response = agent.multiturn_generate_content(prompt, str(json.dumps(pdf_data)))
    response_med = med_agent.multiturn_generate_content(prompt, str(json.dumps(pdf_data)))

    logging.info(response_med)


    medLM, gemini2 = st.columns(2, gap="small")
    # Display assistant response in chat message container
    with medLM:
        st.header("MedLM")
        with st.chat_message("assistant"):
            st.markdown(response_med, unsafe_allow_html=True)
        # Add assistant response to chat history
        st.session_state.messages.append({"role": "assistant", "content": response})

    with gemini2:
        st.header("Gemini 2.0")
        with st.chat_message("assistant"):
            st.markdown(response, unsafe_allow_html=True)
        # Add assistant response to chat history
        # st.session_state.messages.append({"role": "assistant", "content": response_med})




